name: "Build & deploy vector tiles"

on:
  push:
    branches: [ main ]
  pull_request:

env:
  REGION: africa
  AREA: kenya
  IMAGE: ghcr.io/jinigarashi/tilemaker:pr-1
  PMTILES_VERSION: 1.8.0

jobs:

  tilemaker-build:
    name: Generate vector tiles by tilemaker
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Download PBF file
      run: |
        mkdir data
        curl -L http://download.geofabrik.de/${{ env.REGION }}/${{ env.AREA }}-latest.osm.pbf -o ./data/${{ env.AREA }}.osm.pbf

    - name: pull docker image
      run: docker pull ${{ env.IMAGE }}

    - name: Build openmaptiles-compatible mbtiles files of given area
      run: docker run -v $(pwd)/data:/srv ${{ env.IMAGE }} --input=/srv/${{ env.AREA }}.osm.pbf --output=/srv/${{ env.AREA }}.mbtiles

    - name: Download pmtiles converter
      run: |
        curl -L https://github.com/protomaps/go-pmtiles/releases/download/v${{ env.PMTILES_VERSION }}/go-pmtiles_${{ env.PMTILES_VERSION }}_Linux_arm64.tar.gz -o go-pmtiles.tar.gz
        tar -xvzf go-pmtiles.tar.gz

    - name: Convert mbtiles to pmtiles
      run: pmtiles convert ./data/${{ env.AREA }}.mbtiles ./data/${{ env.AREA }}.pmtiles

    - name: clean deploy folder
      run: |
        rm ./data/${{ env.AREA }}.osm.pbf
        rm ./data/${{ env.AREA }}.mbtiles

    - name: deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4.4.3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: data # The folder the action should deploy.